CREATE TABLE IF NOT EXISTS products (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT NOT NULL,
 description TEXT DEFAULT '',
 price REAL NOT NULL DEFAULT 0,
 stock INTEGER NOT NULL DEFAULT 0,
 emoji TEXT DEFAULT '🎂',
 image_url TEXT DEFAULT '',
 created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
